### ISSUE TITLE
SMS settings

### ISSUE THREAD

**Issue by abshkd** [dotansimha/meteor-whatsapp-clone-step-by-step#2]
The part about SMS settings was not clear to me. I am assuming the "üse SMS settings" also goes into sms.js but the json part? I dont see it in your repo either. No file name mentioned in the post.
Great tutorial. thank you. I was looking to learn ionic and now i find this  much more useful resource.
Please do respond.

**Comment by dotansimha** [comment]
Hi @abshkd !
My repo does not contains the SMS config file, because in order to use the SMS feature, you will need an account in twilio with credits.
If there is no SMS config file, then the message wont sent, and instead, they will be printed to the server's log so you can debug and use the verification code.

You can find more information about "accounts-phone" package here: https://github.com/okland/accounts-phone
